### PR TITLE
Adjust to https://github.com/homalg-project/CAP_project/pull/654

### PR DESCRIPTION
**Pull request by zickgraf**

### CODE REVIEW

**Comment by zickgraf** [comment]
Please merge with failing CI due to circular dependencies.

**Comment by mohamed-barakat** [comment]
These are breaking releases. Wouldn't it make sense to bump the version of CAP and make the dependency here explicit?

**Comment by zickgraf** [comment]
It would make sense, but there will be further changes in the coming days, so I would prefer to just bump the version once when all changes are done to save time.

**Comment by mohamed-barakat** [comment]
I agree

**Pull request merged**
